In [1]:
from utils.prompts import create_in_context_examples_prompt_auto, BINARY_TASK_INSTRUCTION
from dataset.utils import ClaudetteDataset, get_binary_labels
from utils.llm_cerebras import get_llm_task_response
import pandas as pd

In [6]:
dataset = ClaudetteDataset()
fair10 = dataset.fetch_rows_by_label('test', 0).sample(10)

In [8]:
get_binary_labels(pd.concat([dataset.sample_rows_from_all_unfair_labels('train', 1), dataset.fetch_rows_by_label('train', 0).sample(9)]))

                                                   text  output
0     you and we must file in arbitration any claim ...  UNFAIR
1     we may take any of these actions at any time ,...  UNFAIR
2     however , foursquare reserves the right to -lr...  UNFAIR
3     in the event this agreement to arbitrate does ...  UNFAIR
4     for others outside of designated countries , i...  UNFAIR
5     to the extent permitted by law , the total lia...  UNFAIR
6     if you use our services , you agree to the ter...  UNFAIR
7     either grammarly or you may terminate this agr...  UNFAIR
8     by using the service , you agree to be bound b...  UNFAIR
3107  the dispute will not be consolidated with any ...    FAIR
1799  you may print out this document or save the fi...    FAIR
3731  the member or subscriber generally has the ess...    FAIR
5787  a -rrb- alibaba.com is able to demonstrate tha...    FAIR
1942  for zalando partner products section a and sec...    FAIR
4382  this service requires that you login to a soci...    FAIR
5653  you agree that -lrb- a -rrb- you will not copy...    FAIR
5776  all title , ownership and intellectual propert...    FAIR
3043  if we delay exercising or fail to exercise or ...    FAIR

In [7]:
fair10

,id,document,label,label_type,text,label_indices
3162,15409,Spotify,0,[],if you have any questions concerning the spoti...,[0]
2238,12508,Vimeo,0,[],"notwithstanding the foregoing , this agreement...",[0]
3056,15303,Spotify,0,[],"specifically , you agree that you shall not --...",[0]
2177,12447,Vimeo,0,[],"vimeo has the right , but not the obligation ,...",[0]
557,3156,Viber,0,[],you agree to notify viber immediately of any u...,[0]
2808,14875,Courchsurfing,0,[],"in addition , the look and feel of the service...",[0]
3643,19526,Zara,0,[],we select only items of the highest quality bu...,[0]
3685,19568,Zara,0,[],we will use our reasonable endeavours to bring...,[0]
1901,11656,Habbo,0,[],sulake reserves the right to remove or reclaim...,[0]
792,6120,Netflix,0,[],visit our website and click on the `` billing ...,[0]

In [ ]:
for text in fair10['text']:
    print(
        get_llm_task_response(
            user_prompt=text,
            system_prompt=BINARY_TASK_INSTRUCTION,
            few_shot_examples=create_in_context_examples_prompt_auto(
                pd.concat([dataset.sample_rows_from_all_unfair_labels('train', 1), dataset.fetch_rows_by_label('train', 0).sample(9)])
            )
        ).content
    )

FAIR
FAIR
UNFAIR
UNFAIR
FAIR
UNFAIR
UNFAIR
FAIR
UNFAIR
FAIR

In [9]:
pd.concat([dataset.sample_rows_from_all_unfair_labels('train', 1), dataset.fetch_rows_by_label('train', 0).sample(9)])

,id,document,label,label_type,text,label_indices
0,17387,WeChat,1,['A'],the seat of the arbitration will be hong kong .,[1]
1,3809,Tripadvisor,1,"['CH', 'LTD', 'TER']",tripadvisor may also impose limits on certain ...,"[2, 6, 8]"
2,791,musically,1,['CR'],the company 's intellectual property policy is...,[3]
3,4242,DeviantArt,1,['J'],any disputes arising under or in connection wi...,[4]
4,1463,WeTransfer,1,['LAW'],these terms of service are governed by dutch l...,[5]
5,59,Mozilla,1,['LTD'],some jurisdictions do not allow the exclusion ...,[6]
6,18385,imgur,1,"['PINC', 'USE']",using our app to do anything other than access...,"[7, 9]"
7,3808,Tripadvisor,1,"['CR', 'TER']","tripadvisor may change , suspend or discontinu...","[3, 8]"
8,4183,DeviantArt,1,['USE'],"by using our service , you agree to be bound b...",[9]
1071,2844,Expedia,0,[],"with certain hotels , you may be presented wit...",[0]
5742,13632,Alibaba,0,[],such risks also include the risks that consume...,[0]
6445,14625,Evernote,0,[],"upon receipt of any such request , we will end...",[0]
3045,7898,Headspace,0,[],"in these terms , unless the context requires o...",[0]
3020,7873,Headspace,0,[],-lrb- c -rrb- a description of where the mater...,[0]
1634,4352,9gag,0,[],"9gag , inc retains the right to create limits ...",[0]
7322,17413,WeChat,0,[],if you have already used a portion of the rele...,[0]
6061,13951,Grindr,0,[],any relief awarded can not affect other users .,[0]
46,46,Mozilla,0,[],for more information on how to report claims o...,[0]

In [9]:
dataset = ClaudetteDataset()

In [10]:
eval_df = get_binary_labels(dataset.get_dataset('test'))
eval_data = list(eval_df.itertuples(index=False, name=None))
eval_data

[('thank you for using pinterest !', 'FAIR'),
 ("these terms of service -lrb- `` terms '' -rrb- govern your access to and use of the pinterest website , apps , apis , and widgets -lrb- `` pinterest '' or the `` service '' -rrb- .",
  'FAIR'),
 ('please read these terms carefully , and contact us if you have any questions .',
  'FAIR'),
 ('by accessing or using pinterest , you agree to be bound by these terms , our privacy policy , our cookies policy and our community guidelines .',
  'UNFAIR'),
 ('every company has its terms .', 'FAIR'),
 ('pinterest helps you discover and do what you love .', 'FAIR'),
 ('to do that , we show you things we think will be relevant , interesting and personal to you based on your onsite and offsite activity .',
  'FAIR'),
 ('to provide our service , we need to be able to identify you and your interests .',
  'FAIR'),
 ('some of the things we show you are promoted by advertisers .', 'FAIR'),
 ('as part of our service we try to ensure that even promoted content is relevant and interesting to you .',
  'FAIR'),
 ('you can identify promoted content because it will be clearly labelled .',
  'FAIR'),
 ('pinterest helps you discover and do what you love .', 'FAIR'),
 ("it 's customized to you .", 'FAIR'),
 ('we need to know what you like to make everything on pinterest relevant to you .',
  'FAIR'),
 ('you may use pinterest only if you can legally form a binding contract with pinterest , and only in compliance with these terms and all applicable laws .',
  'FAIR'),
 ('when you create your pinterest account , you must provide us with accurate and complete information .',
  'FAIR'),
 ('any use or access by anyone under the age of 13 is not allowed .', 'FAIR'),
 ("if you 're based in the eea , you may only use pinterest if you are over the age at which you can provide consent to data processing under the laws of your country or if verifiable parental consent for your use of pinterest has been provided to us .",
  'FAIR'),
 ('using pinterest may include downloading software to your computer , phone , tablet , or other device .',
  'FAIR'),
 ('you agree that we may automatically update that software , and these terms will apply to any updates .',
  'FAIR'),
 ('subject to these terms and our policies -lrb- including our community guidelines -rrb- , we grant you a limited , non-exclusive , non-transferable , and revocable license to use our service .',
  'FAIR'),
 ('if you want to use pinterest for commercial purposes you must create a business account and agree to our business terms of service .',
  'FAIR'),
 ("if you do open an account for a company , organization , or other entity , then `` you '' includes you and that entity , and you promise that you are authorized to grant all permissions and licenses provided in these terms and bind the entity to these terms , and that you agree to these terms on the entity 's behalf .",
  'FAIR'),
 ("you can not use pinterest if you 're under 13 -lrb- or older in some countries -rrb- .",
  'FAIR'),
 ('also , if you are using pinterest for work , you need to set up a business account .',
  'FAIR'),
 ('pinterest allows you to post content , including photos , comments , links , and other materials .',
  'FAIR'),
 ("anything that you post or otherwise make available on pinterest is referred to as `` user content . ''",
  'FAIR'),
 ('you retain all rights in , and are solely responsible for , the user content you post to pinterest .',
  'FAIR'),
 ('if you post your content on pinterest , it still belongs to you .', 'FAIR'),
 ('how pinterest and other users can use your content', 'FAIR'),
 ('you grant pinterest and our users a non-exclusive , royalty-free , transferable , sublicensable , worldwide license to use , store , display , reproduce , save , modify , create derivative works , perform , and distribute your user content on pinterest solely for the purposes of operating , developing , providing , and using pinterest .',
  'FAIR'),
 ('nothing in these terms restricts other legal rights pinterest may have to user content , for example under other licenses .',
  'FAIR'),
 ("we reserve the right to remove or modify user content , or change the way it 's used in pinterest , for any reason .",
  'UNFAIR'),
 ('this includes user content that we believe violates these terms , our community guidelines , or any other policies .',
  'UNFAIR'),
 ('if you post your content on pinterest , we can show it to people and others can save it .',
  'FAIR'),
 ("do n't post porn or spam or be a jerk to other people on pinterest .",
  'FAIR'),
 ('how long we keep your content', 'FAIR'),
 ('following termination or deactivation of your account , or if you remove any user content from pinterest , we may keep your user content for a reasonable period of time for backup , archival , or audit purposes .',
  'FAIR'),
 ('pinterest and its users may retain and continue to use , store , display , reproduce , re-pin , modify , create derivative works , perform , and distribute any of your user content that other users have stored or shared on pinterest .',
  'FAIR'),
 ('if you choose to post content , you give us permission to use it to provide and improve pinterest .',
  'FAIR'),
 ('copies of content shared with others may remain even after you delete the content from your account .',
  'FAIR'),
 ('we value hearing from our users , and are always interested in learning about ways we can make pinterest more awesome .',
  'FAIR'),
 ('if you choose to submit comments , ideas or feedback , you agree that we are free to use them without any restriction or compensation to you .',
  'FAIR'),
 ("by accepting your submission , pinterest does n't waive any rights to use similar or related feedback previously known to pinterest , or developed by its employees , or obtained from sources other than you .",
  'FAIR'),
 ('we can use your suggestions to make pinterest better .', 'FAIR'),
 ('pinterest has adopted and implemented the pinterest copyright policy in accordance with the digital millennium copyright act and other applicable copyright laws .',
  'FAIR'),
 ('for more information , please read our copyright policy .', 'FAIR'),
 ('we care about the security of our users .', 'FAIR'),
 ("while we work to protect the security of your content and account , pinterest ca n't guarantee that unauthorized third parties wo n't be able to defeat our security measures .",
  'FAIR'),
 ('we ask that you keep your password secure .', 'FAIR'),
 ('please notify us immediately of any compromise or unauthorized use of your account .',
  'FAIR'),
 ('you can help us fight spammers by keeping these security tips in mind .',
  'FAIR'),
 ('third party links , sites , and services', 'FAIR'),
 ('pinterest may contain links to third party websites , advertisers , services , special offers , or other events or activities that are not owned or controlled by pinterest .',
  'FAIR'),
 ("we do n't endorse or assume any responsibility for any such third party sites , information , materials , products , or services .",
  'FAIR'),
 ('if you access any third party website , service , or content from pinterest , you do so at your own risk and you agree that pinterest has no liability arising from your use of or access to any third party website , service , or content .',
  'FAIR'),
 ('pinterest has links to content off of pinterest .', 'FAIR'),
 ("most of that stuff is awesome , but we 're not responsible when it 's not .",
  'FAIR'),
 ('pinterest may terminate or suspend your right to access or use pinterest for any reason on appropriate notice .',
  'UNFAIR'),
 ('we may terminate or suspend your access immediately and without notice if we have a good reason , including any violation of our community guidelines .',
  'UNFAIR'),
 ('upon termination , you continue to be bound by sections 3 and 8 of these terms .',
  'FAIR'),
 ('pinterest is provided to you for free .', 'FAIR'),
 ('we reserve the right to refuse service to anyone , but we will provide appropriate notice .',
  'FAIR'),
 ('if you use pinterest for commercial purposes -lrb- i.e. , you are not a consumer -rrb- without agreeing to our business terms as required by section 2 -lrb- c -rrb- of these terms , you agree to indemnify and hold harmless pinterest inc , pinterest europe ltd , their affiliates and their respective officers , directors , employees and agents , from and against any claims , suits , proceedings , disputes , demands , liabilities , damages , losses , costs and expenses , including , without limitation , reasonable legal and accounting fees -lrb- including costs of defense of claims , suits or proceedings brought by third parties -rrb- , in any way related to your access to or use of our service , your user content , or your breach of any of these terms .',
  'FAIR'),
 ('if we are sued because of something your business does on pinterest , you have to pay our costs .',
  'FAIR'),
 ('also , you should have created a business account and agreed to our business terms in the first place .',
  'FAIR'),
 ("our service and all content on pinterest is provided on an `` as is '' basis without warranty of any kind , whether express or implied .",
  'FAIR'),
 ('pinterest specifically disclaims any and all warranties and conditions of merchantability , fitness for a particular purpose , and non-infringement , and any warranties arising out of course of dealing or usage of trade .',
  'FAIR'),
 ('pinterest takes no responsibility and assumes no liability for any user content that you or any other person or third party posts or sends using our service .',
  'FAIR'),
 ("you understand and agree that you may be exposed to user content that 's inaccurate , objectionable , inappropriate for children , or otherwise unsuited to your purpose .",
  'FAIR'),
 ("if you 're a consumer in the eea , we do n't exclude or limit any liability for gross negligence , intent , or death or personal injury caused by our negligence or willful misconduct .",
  'FAIR'),
 ('unfortunately , people post bad stuff on services like pinterest .',
  'FAIR'),
 ('we take that kind of thing seriously but you still might run into it before we have a chance to take it down .',
  'FAIR'),
 ('if you see bad stuff , please report it to us here .', 'FAIR'),
 ('to the maximum extent permitted by law , pinterest shall not be liable for any indirect , incidental , special , consequential or punitive damages , or any loss of profits or revenues , whether incurred directly or indirectly , or any loss of data , use , goodwill , or other intangible losses , resulting from -lrb- a -rrb- your access to or use of or inability to access or use the service ; -lrb- b -rrb- any conduct or content of any third party on the service , including without limitation , any defamatory , offensive or illegal conduct of other users or third parties ; or -lrb- c -rrb- unauthorized access , use or alteration of your transmissions or content .',
  'UNFAIR'),
 ("in no event shall pinterest 's aggregate liability for all claims relating to the service exceed one hundred u.s. dollars -lrb- u.s. $ 100.00 -rrb- .",
  'UNFAIR'),
 ("if we cause damage to you and you 're a consumer in the eea , the above does n't apply .",
  'FAIR'),
 ("instead , pinterest 's liability will be limited to foreseeable damages arising due to a breach of material contractual obligations typical for this type of contract .",
  'UNFAIR'),
 ("pinterest is n't liable for damages that result from a non-material breach of any other applicable duty of care .",
  'UNFAIR'),
 ("this limitation of liability wo n't apply to any statutory liability that can not be limited , to liability for death or personal injury caused by our negligence or willful misconduct , or if and to exclude our responsibility for something we have specifically promised to you .",
  'UNFAIR'),
 ("we are building the best service we can for you but we ca n't promise it will be perfect .",
  'FAIR'),
 ("we 're not liable for various things .", 'UNFAIR'),
 ("if you think we are , let 's try to work it out like adults .", 'FAIR'),
 ('for any dispute you have with pinterest , you agree to first contact us and try to resolve the dispute with us informally .',
  'FAIR'),
 ('if we need to contact you , we will do so at the email address on your pinterest account .',
  'FAIR'),
 ("if pinterest has n't been able to resolve the dispute with you informally , we each agree to resolve any claim , dispute , or controversy -lrb- excluding claims for injunctive or other equitable relief -rrb- arising out of or in connection with or relating to these terms through binding arbitration or -lrb- for qualifying claims -rrb- in small claims court .",
  'UNFAIR'),
 ('arbitration is a more informal way to resolve our disagreements than a lawsuit in court .',
  'FAIR'),
 ('for instance , arbitration uses a neutral arbitrator instead of a judge or jury , involves more limited discovery , and is subject to very limited review by courts .',
  'FAIR'),
 ('although the process is more informal , arbitrators can award the same damages and relief that a court can award .',
  'FAIR'),
 ('you agree that , by agreeing to these terms of service , the u.s. federal arbitration act governs the interpretation and enforcement of this provision , and that you and pinterest are each waiving the right to a trial by jury or to participate in a class action .',
  'UNFAIR'),
 ('the arbitrator has exclusive authority to resolve any dispute relating to the interpretation , applicability , or enforceability of this binding arbitration agreement .',
  'UNFAIR'),
 ('this arbitration provision shall survive termination of this agreement and the termination of your pinterest account .',
  'FAIR'),
 ("any arbitration will be administered by the american arbitration association -lrb- `` aaa '' -rrb- under the consumer arbitration rules then in effect for the aaa , except as provided herein .",
  'UNFAIR'),
 ('you can find their forms at www.adr.org .', 'FAIR'),
 ('unless you and pinterest agree otherwise , the arbitration will be conducted in the county -lrb- or parish -rrb- where you reside .',
  'FAIR'),
 ('each party will be responsible for paying any aaa filing , administrative and arbitrator fees in accordance with aaa rules , except that pinterest will pay for your reasonable filing , administrative , and arbitrator fees if your claim for damages does not exceed $ 75,000 and is non-frivolous -lrb- as measured by the standards set forth in federal rule of civil procedure 11 -lrb- b -rrb- -rrb- .',
  'FAIR'),
 ('if your claim is for $ 10,000 or less , we agree that you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator , through a telephonic hearing , or by an in-person hearing as established by the aaa rules .',
  'FAIR'),
 ('if your claim exceeds $ 10,000 , the right to a hearing will be determined by the aaa rules .',
  'UNFAIR'),
 ('regardless of the manner in which the arbitration is conducted , the arbitrator shall issue a reasoned written decision explaining the essential findings and conclusions on which the award is based , and any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction .',
  'FAIR'),
 ('nothing in this section shall prevent either party from seeking injunctive or other equitable relief from the courts , including for matters related to data security , intellectual property or unauthorized access to the service .',
  'FAIR'),
 ("all claims must be brought in the parties ' individual capacity , and not as a plaintiff or class member in any purported class or representative proceeding , and , unless we agree otherwise , the arbitrator may not consolidate more than one person 's claims .",
  'FAIR'),
 ('you agree that , by entering into these terms , you and pinterest are each waiving the right to a trial by jury or to participate in a class action .',
  'FAIR'),
 ('nothing in these terms of service shall affect any non-waivable statutory rights that apply to you .',
  'FAIR'),
 ("to the extent any claim , dispute or controversy regarding pinterest or our service is n't arbitrable under applicable laws or otherwise : you and pinterest both agree that any claim or dispute regarding pinterest will be resolved exclusively in accordance with section 12 of these terms .",
  'FAIR'),
 ("if you 're a consumer in the eea , section 11 does n't apply to you .",
  'FAIR'),
 ('these terms shall be governed by the laws of the state of california , without respect to its conflict of laws principles .',
  'UNFAIR'),
 ('if you are not a consumer in the eea , the exclusive place of jurisdiction for all disputes arising from or in connection with this agreement is san francisco county , california , or the united states district court for the northern district of california and our dispute will be determined under california law .',
  'UNFAIR'),
 ("if you are a consumer in the eea , this wo n't deprive you of any protection you have under the law of the country where you live and access to the courts in that country .",
  'FAIR'),
 ('the bay area is beautiful this time of year .', 'FAIR'),
 ("it does n't matter what time of year it is , that 's what 's so great !",
  'FAIR'),
 ("anyway , you 'll have to sue us here .", 'FAIR'),
 ("in the eea , this applies if you 're a merchant , but not if you 're a consumer .",
  'FAIR'),
 ('if you are a consumer in the eea , you can sue us in your home courts .',
  'FAIR'),
 ('notification procedures and changes to these terms', 'FAIR'),
 ("we reserve the right to determine the form and means of providing notifications to you , and you agree to receive legal notices electronically if that 's what we decide .",
  'FAIR'),
 ('we may revise these terms from time to time and the most current version will always be posted on our website .',
  'UNFAIR'),
 ("if a revision , in our discretion , is material , we 'll notify you .",
  'FAIR'),
 ('by continuing to access or use pinterest after revisions become effective , you agree to be bound by the new terms .',
  'UNFAIR'),
 ("if you do n't agree to the new terms , please stop using pinterest .",
  'UNFAIR'),
 ("if we 're making a big change to the terms , we 'll let you know .",
  'FAIR'),
 ("if you do n't like the new terms , please stop using pinterest .", 'FAIR'),
 ('these terms , and any rights and licenses granted hereunder , may not be transferred or assigned by you , but may be assigned by pinterest without restriction .',
  'FAIR'),
 ('any attempted transfer or assignment in violation hereof shall be null and void .',
  'FAIR'),
 ("if you 're a consumer in the eea , either you or pinterest may assign this agreement , and any rights and licences granted under it , to a third party .",
  'FAIR'),
 ('in case of such an assignment by pinterest , you are entitled to terminate the agreement with immediate effect by deactivating your account .',
  'FAIR'),
 ('pinterest will provide you with reasonable notice of any such assignment .',
  'FAIR'),
 ('these terms , together with the privacy policy and any amendments and any additional agreements you may enter into with pinterest shall constitute the entire agreement between you and pinterest concerning the service .',
  'UNFAIR'),
 ('if any provision of these terms is deemed invalid , then that provision will be limited or eliminated to the minimum extent necessary , and the remaining provisions of these terms will remain in full force and effect .',
  'FAIR'),
 ("no waiver of any term of these terms shall be deemed a further or continuing waiver of such term or any other term , and pinterest 's failure to assert any right or provision under these terms shall not constitute a waiver of such right or provision .",
  'FAIR'),
 ('if you live in the united states , these terms are a contract between you and pinterest inc. , 651 brannan street , san francisco , ca 94103 .',
  'FAIR'),

In [ ]:
dataset.sample_rows_by_all_labels('train', 2)

,id,document,label,label_type,text,label_indices
0,18783,Grammarly,0,[],"you are solely responsible for all text , docu...",[0]
1,14508,Rovio,0,[],some jurisdictions do not allow the exclusion ...,[0]
2,12209,Weebly,1,['A'],any claim relating to these terms that is not ...,[1]
3,12747,Shazam,1,['A'],you may only resolve disputes with us on an in...,[1]
4,1338,WeTransfer,1,['CH'],1.3 we change the terms every so often .,[2]
5,8023,VeryChic,1,['CH'],verychic reserves the right to make modificati...,[2]
6,13849,Grindr,1,['CR'],"nonetheless , grindr reserves the right to pre...",[3]
7,16861,Electronic_Arts,1,['CR'],instead of termination and prior to any termin...,[3]
8,16910,Electronic_Arts,1,"['J', 'LAW']","if you in live in any other country , -lrb- i ...","[4, 5]"
9,20276,Foursquare,1,['J'],all disputes or claims arising out of or relat...,[4]
10,1468,WeTransfer,1,"['J', 'LAW']",any disputes regarding these terms of service ...,"[4, 5]"
11,16358,TikTok,1,['LAW'],"these terms , their subject matter and their f...",[5]
12,20292,Foursquare,1,['LTD'],foursquare shall not be liable for any failure...,[6]
13,867,musically,1,['LTD'],in no event will any company party be liable f...,[6]
14,1331,WeTransfer,1,"['PINC', 'USE']","if you use our services , you agree to the ter...","[7, 9]"
15,14482,Rovio,1,"['PINC', 'USE']","by installing , accessing or using the rovio s...","[7, 9]"
16,17811,Microsoft,1,"['CR', 'TER']",if you have more content stored in your onedri...,"[3, 8]"
17,16814,Electronic_Arts,1,['TER'],if you or someone using your ea account violat...,[8]
18,9679,Match,1,['USE'],"therefore , by creating an account , the membe...",[9]
19,20289,Foursquare,1,['USE'],your continued use of the service following th...,[9]